In [1]:
import os
print (os.getenv("COINGECKO_API_KEY"))

CG-6bJ3mSAgrpEho2mjo1mVuS2o

In [2]:
import os
from pathlib import Path

# Set root folder
project_root = Path.cwd()
if project_root.name == "notebooks":
    project_root = project_root.parent

os.chdir(project_root)
print("CWD =", Path.cwd())

CWD = c:\Users\sia\Desktop\capstone\src\Agentic-Crypto-Return-Service

# Raw Data

We get data from two sources, YahooFinance and CoinGeko. we were planning to get data mainly from CoinGeko and just use YahooFinance for Cross checking and validation, but unfortunately CoinGeko sells its api and the developer api key only returns data for 365 days. So, we had to switch to YahooFinance as the primary source.

### Raw Data .... OHLCV

In [3]:
from core.pipelines.daily_ohlcv_pipeline import run_one_ticker , run_all

# To run the pipeline for a single ticker we can use the `run_one_ticker` function. useful for test and debug
# run_one_ticker("BTC-USD")


# To run the pipeline for all tickers we can use the `run_all` function. This will run the pipeline for all tickers in the Coins.json.
run_all()

[BTC-USD] up-to-date (last_date=2026-03-15). No fetch needed.
[BTC-USD] inserted rows: 0
[ETH-USD] up-to-date (last_date=2026-03-15). No fetch needed.
[ETH-USD] inserted rows: 0
[BNB-USD] up-to-date (last_date=2026-03-15). No fetch needed.
[BNB-USD] inserted rows: 0
[XRP-USD] up-to-date (last_date=2026-03-15). No fetch needed.
[XRP-USD] inserted rows: 0
[SOL-USD] up-to-date (last_date=2026-03-15). No fetch needed.
[SOL-USD] inserted rows: 0
[DOGE-USD] up-to-date (last_date=2026-03-15). No fetch needed.
[DOGE-USD] inserted rows: 0
[ADA-USD] up-to-date (last_date=2026-03-15). No fetch needed.
[ADA-USD] inserted rows: 0
[LINK-USD] up-to-date (last_date=2026-03-15). No fetch needed.
[LINK-USD] inserted rows: 0
[AVAX-USD] up-to-date (last_date=2026-03-15). No fetch needed.
[AVAX-USD] inserted rows: 0
[FLOKI-USD] up-to-date (last_date=2026-03-15). No fetch needed.
[FLOKI-USD] inserted rows: 0

In [4]:
from core.storage.market_data_repository import get_market_data_repository

repo = get_market_data_repository()
df = repo.read_ohlcv(yahoo_ticker="BTC-USD")

df.head(10)

,date,open,high,low,close,volume,ticker
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,21056800.0,BTC-USD
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,34483200.0,BTC-USD
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,37919700.0,BTC-USD
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,36863600.0,BTC-USD
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,26580100.0,BTC-USD
5,2014-09-22,399.100006,406.915985,397.130005,402.152008,24127600.0,BTC-USD
6,2014-09-23,402.092011,441.557007,396.196991,435.790985,45099500.0,BTC-USD
7,2014-09-24,435.751007,436.112000,421.131989,423.204987,30627700.0,BTC-USD
8,2014-09-25,423.156006,423.519989,409.467987,411.574005,26814400.0,BTC-USD
9,2014-09-26,411.428986,414.937988,400.009003,404.424988,21460800.0,BTC-USD

### Raw Data .... Marketcap

In [5]:
from core.pipelines.marketcap_pipeline import run_one_symbol , run_all


run_all()

[BTC] up-to-date (last_date=2026-03-15). No fetch needed.
[BTC] inserted rows: 0
[ETH] up-to-date (last_date=2026-03-15). No fetch needed.
[ETH] inserted rows: 0
[BNB] up-to-date (last_date=2026-03-15). No fetch needed.
[BNB] inserted rows: 0
[XRP] up-to-date (last_date=2026-03-15). No fetch needed.
[XRP] inserted rows: 0
[SOL] up-to-date (last_date=2026-03-15). No fetch needed.
[SOL] inserted rows: 0
[DOGE] added -1 new rows (days_requested=365)
[DOGE] inserted rows: -1
[ADA] added -1 new rows (days_requested=365)
[ADA] inserted rows: -1
[LINK] added -1 new rows (days_requested=365)
[LINK] inserted rows: -1
[AVAX] added -1 new rows (days_requested=365)
[AVAX] inserted rows: -1
[FLOKI] added -1 new rows (days_requested=365)
[FLOKI] inserted rows: -1

In [6]:
from core.storage.market_data_repository import get_market_data_repository

repo = get_market_data_repository()
df = repo.read_market_cap(symbol="ETH")

df.head(10)

         date    market_cap coingecko_id symbol
0  2025-03-16  2.339703e+11     ethereum    ETH
1  2025-03-17  2.276890e+11     ethereum    ETH
2  2025-03-18  2.327254e+11     ethereum    ETH
3  2025-03-19  2.331522e+11     ethereum    ETH
4  2025-03-20  2.484341e+11     ethereum    ETH
5  2025-03-21  2.389842e+11     ethereum    ETH
6  2025-03-22  2.369800e+11     ethereum    ETH
7  2025-03-23  2.387533e+11     ethereum    ETH
8  2025-03-24  2.414043e+11     ethereum    ETH
9  2025-03-25  2.506487e+11     ethereum    ETH

# Processed Data

In [7]:
from core.pipelines.build_processed_daily import build_all , build_one
# build_one("BTC","BTC-USD")


build_all()

[BTC] processed rows inserted: 0
[ETH] processed rows inserted: 0
[BNB] processed rows inserted: 0
[XRP] processed rows inserted: 0
[SOL] processed rows inserted: 0
[DOGE] processed rows inserted: 0
[ADA] processed rows inserted: 0
[LINK] processed rows inserted: 0
[AVAX] processed rows inserted: 0
[FLOKI] processed rows inserted: 0

In [8]:
from core.storage.market_data_repository import get_market_data_repository

repo = get_market_data_repository()
df = repo.read_processed(symbol="ETH")

df.head(10)
df.tail(10)

,date,open,high,low,close,volume,market_cap,ticker
3038,2026-03-05,2126.560547,2163.036133,2056.019043,2071.605469,2.238358e+10,2.565364e+11,ETH-USD
3039,2026-03-06,2072.025635,2092.515137,1957.015015,1978.751221,1.973365e+10,2.504116e+11,ETH-USD
3040,2026-03-07,1978.690552,1994.970581,1950.022461,1969.455444,1.023690e+10,2.391651e+11,ETH-USD
3041,2026-03-08,1969.452271,1978.707153,1915.301025,1936.604736,1.631403e+10,2.377054e+11,ETH-USD
3042,2026-03-09,1936.637451,2052.327393,1930.599121,1992.938232,2.401583e+10,2.341305e+11,ETH-USD
3043,2026-03-10,1992.986084,2087.985352,1992.014160,2037.120483,2.355235e+10,2.405688e+11,ETH-USD
3044,2026-03-11,2037.121216,2085.286377,2008.038696,2051.573242,1.903172e+10,2.456463e+11,ETH-USD
3045,2026-03-12,2051.766602,2094.325684,2019.277832,2073.136230,2.062495e+10,2.476461e+11,ETH-USD
3046,2026-03-13,2073.289307,2206.813232,2071.582275,2092.563477,2.934521e+10,2.506369e+11,ETH-USD
3047,2026-03-15,2096.664551,2111.003906,2084.965576,2111.003906,9.753406e+09,2.546321e+11,ETH-USD

# Feature Engineering

In [9]:
from core.pipelines.features_pipeline import run_all


run_all()

[BTC] feature rows inserted: 0
[ETH] feature rows inserted: 0
[BNB] feature rows inserted: 0
[XRP] feature rows inserted: 0
[SOL] feature rows inserted: 0
[DOGE] feature rows inserted: 0
[ADA] feature rows inserted: 0
[LINK] feature rows inserted: 0
[AVAX] feature rows inserted: 0
[FLOKI] feature rows inserted: 0

c:\Users\sia\.conda\envs\mlhub\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\sia\.conda\envs\mlhub\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\sia\.conda\envs\mlhub\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [10]:
from core.storage.market_data_repository import get_market_data_repository

repo = get_market_data_repository()
df = repo.read_features(symbol="BTC")

df.head(10)

,date,open,high,low,close,volume,market_cap,log_ret_1d,log_ret_5d,log_ret_10d,vol_7d,vol_30d,risk_adj_ret_1d,vol_ratio_7d_30d,drawdown_30d,ticker
0,2014-10-17,382.756012,385.477997,375.389008,383.757996,13600700.0,NaN,0.003137,0.013667,0.132345,0.026790,0.039426,0.079569,0.679485,-0.119399,BTC-USD
1,2014-10-18,383.976013,395.157989,378.971008,391.441986,11416800.0,NaN,0.019825,0.002630,0.103539,0.026916,0.037466,0.529154,0.718425,-0.101767,BTC-USD
2,2014-10-19,391.253998,393.938995,386.457001,389.545990,5914570.0,NaN,-0.004855,-0.028655,0.065013,0.023034,0.035087,-0.138383,0.656492,-0.106117,BTC-USD
3,2014-10-20,389.230988,390.084015,378.252014,382.845001,16419000.0,NaN,-0.017352,-0.030681,0.057197,0.020794,0.034557,-0.502125,0.601745,-0.121494,BTC-USD
4,2014-10-21,382.420990,392.645996,380.834015,386.475006,14188900.0,NaN,0.009437,0.010192,0.064597,0.017553,0.034345,0.274770,0.511079,-0.113164,BTC-USD
5,2014-10-22,386.118011,388.575989,382.248993,383.157989,11641300.0,NaN,-0.008620,-0.001565,0.012102,0.017087,0.034325,-0.251123,0.497788,-0.120776,BTC-USD
6,2014-10-23,382.962006,385.048004,356.446991,358.416992,26456900.0,NaN,-0.066750,-0.088140,-0.085511,0.028106,0.032682,-2.042438,0.859986,-0.153089,BTC-USD
7,2014-10-24,358.591003,364.345001,353.304993,358.345001,15585700.0,NaN,-0.000201,-0.083486,-0.112141,0.027887,0.032413,-0.006198,0.860369,-0.129330,BTC-USD
8,2014-10-25,358.610992,359.860992,342.877014,347.270996,18127500.0,NaN,-0.031391,-0.097525,-0.128205,0.025433,0.032503,-0.965792,0.782496,-0.141322,BTC-USD
9,2014-10-26,347.487000,359.221008,343.931000,354.704010,11272500.0,NaN,0.021178,-0.085784,-0.075591,0.029154,0.032782,0.646023,0.889321,-0.115164,BTC-USD