In [1]:
import os
print (os.getenv("COINGECKO_API_KEY"))

CG-6bJ3mSAgrpEho2mjo1mVuS2o

In [2]:
import os
from pathlib import Path

# Set root folder
project_root = Path.cwd()
if project_root.name == "notebooks":
    project_root = project_root.parent

os.chdir(project_root)
print("CWD =", Path.cwd())

CWD = c:\Users\stada\OneDrive\Desktop\Capstone\src\Agentic-Crypto-Return-Service

# Raw Data

We get data from two sources, YahooFinance and CoinGeko. we were planning to get data mainly from CoinGeko and just use YahooFinance for Cross checking and validation, but unfortunately CoinGeko sells its api and the developer api key only returns data for 365 days. So, we had to switch to YahooFinance as the primary source.

### Raw Data .... OHLCV

In [ ]:
from core.pipelines.daily_ohlcv_pipeline import run_one_ticker , run_all

# To run the pipeline for a single ticker we can use the `run_one_ticker` function. useful for test and debug
# run_one_ticker("BTC-USD")


# To run the pipeline for all tickers we can use the `run_all` function. This will run the pipeline for all tickers in the Coins.json.
run_all()

saved: data\raw\ohlcv\BTC-USD_daily.csv
saved: data\raw\ohlcv\ETH-USD_daily.csv
saved: data\raw\ohlcv\BNB-USD_daily.csv
saved: data\raw\ohlcv\XRP-USD_daily.csv
saved: data\raw\ohlcv\SOL-USD_daily.csv
saved: data\raw\ohlcv\DOGE-USD_daily.csv
saved: data\raw\ohlcv\ADA-USD_daily.csv
saved: data\raw\ohlcv\LINK-USD_daily.csv
saved: data\raw\ohlcv\AVAX-USD_daily.csv
saved: data\raw\ohlcv\FLOKI-USD_daily.csv

In [5]:
import pandas as pd

df = pd.read_csv("data/raw/ohlcv/BTC-USD_daily.csv")


df.head(10)

,date,open,high,low,close,volume,ticker
0,2014-09-17,465.864014,468.174011,452.421997,457.334015,21056800,BTC-USD
1,2014-09-18,456.859985,456.859985,413.104004,424.440002,34483200,BTC-USD
2,2014-09-19,424.102997,427.834991,384.532013,394.795990,37919700,BTC-USD
3,2014-09-20,394.673004,423.295990,389.882996,408.903992,36863600,BTC-USD
4,2014-09-21,408.084991,412.425995,393.181000,398.821014,26580100,BTC-USD
5,2014-09-22,399.100006,406.915985,397.130005,402.152008,24127600,BTC-USD
6,2014-09-23,402.092010,441.557007,396.196991,435.790985,45099500,BTC-USD
7,2014-09-24,435.751007,436.112000,421.131989,423.204987,30627700,BTC-USD
8,2014-09-25,423.156006,423.519989,409.467987,411.574005,26814400,BTC-USD
9,2014-09-26,411.428986,414.937988,400.009003,404.424988,21460800,BTC-USD

### Raw Data .... Marketcap

In [6]:
from core.pipelines.marketcap_pipeline import run_one_symbol , run_all

# To run the pipeline for a single ticker we can use the `run_one_ticker` function. useful for test and debug
# run_one_symbol("bitcoin")


# To run the pipeline for all tickers we can use the `run_all` function. This will run the pipeline for all tickers in the Coins.json.
run_all()

[BTC] added 3 new rows (days_requested=4)
saved: data\raw\market_cap\BTC_daily.csv
[ETH] added 3 new rows (days_requested=4)
saved: data\raw\market_cap\ETH_daily.csv
[BNB] added 0 new rows (days_requested=4)
saved: data\raw\market_cap\BNB_daily.csv
[XRP] added 0 new rows (days_requested=365)
saved: data\raw\market_cap\XRP_daily.csv
[SOL] added 0 new rows (days_requested=365)
saved: data\raw\market_cap\SOL_daily.csv
[DOGE] added 0 new rows (days_requested=365)
saved: data\raw\market_cap\DOGE_daily.csv
[ADA] added 0 new rows (days_requested=365)
saved: data\raw\market_cap\ADA_daily.csv
[LINK] added 0 new rows (days_requested=365)
saved: data\raw\market_cap\LINK_daily.csv
[AVAX] added 0 new rows (days_requested=365)
saved: data\raw\market_cap\AVAX_daily.csv
[FLOKI] added 0 new rows (days_requested=365)
saved: data\raw\market_cap\FLOKI_daily.csv

In [7]:
df = pd.read_csv("data/raw/market_cap/BTC_daily.csv")


df.head(10)

         date    market_cap coingecko_id symbol
0  2025-02-09  1.914212e+12      bitcoin    BTC
1  2025-02-10  1.913069e+12      bitcoin    BTC
2  2025-02-11  1.930743e+12      bitcoin    BTC
3  2025-02-12  1.898789e+12      bitcoin    BTC
4  2025-02-13  1.936842e+12      bitcoin    BTC
5  2025-02-14  1.914315e+12      bitcoin    BTC
6  2025-02-15  1.931657e+12      bitcoin    BTC
7  2025-02-16  1.934308e+12      bitcoin    BTC
8  2025-02-17  1.905012e+12      bitcoin    BTC
9  2025-02-18  1.898998e+12      bitcoin    BTC

# Processed Data

In [8]:
from core.pipelines.build_processed_daily import build_all , build_one
# build_one("BTC","BTC-USD")


build_all()

built: data\processed\daily\BTC_daily.csv
built: data\processed\daily\ETH_daily.csv
built: data\processed\daily\BNB_daily.csv
built: data\processed\daily\XRP_daily.csv
built: data\processed\daily\SOL_daily.csv
built: data\processed\daily\DOGE_daily.csv
built: data\processed\daily\ADA_daily.csv
built: data\processed\daily\LINK_daily.csv
built: data\processed\daily\AVAX_daily.csv
built: data\processed\daily\FLOKI_daily.csv

In [14]:
df = pd.read_csv("data/processed/daily/BTC_daily.csv")
print (f"first 5 rows of df: \n{df.head(5)}")
print ("="*50 , "\n")
print (f"last 5 rows of df: \n{df.tail(5)}")
print ("="*50 , "\n")

print (f"Null values in df: \n{df.isnull().sum()}")

first 5 rows of df:
         date        open        high         low       close    volume  \
0  2014-09-17  465.864014  468.174011  452.421997  457.334015  21056800
1  2014-09-18  456.859985  456.859985  413.104004  424.440002  34483200
2  2014-09-19  424.102997  427.834991  384.532013  394.795990  37919700
3  2014-09-20  394.673004  423.295990  389.882996  408.903992  36863600
4  2014-09-21  408.084991  412.425995  393.181000  398.821014  26580100

    ticker  market_cap
0  BTC-USD         NaN
1  BTC-USD         NaN
2  BTC-USD         NaN
3  BTC-USD         NaN
4  BTC-USD         NaN
==================================================

last 5 rows of df:
            date          open          high           low         close  \
4160  2026-02-06  62704.453125  71681.304688  60074.203125  70555.390625
4161  2026-02-07  70553.796875  71611.148438  67364.445312  69281.968750
4162  2026-02-09  70306.117188  70668.898438  70205.554688  70205.554688
4163  2026-02-10  70137.390625  70464.265625  67913.093750  68793.960938
4164  2026-02-12  67025.554688  67527.382812  67025.554688  67479.554688

            volume   ticker    market_cap
4160  114674259489  BTC-USD  1.262033e+12
4161   62347107663  BTC-USD  1.410204e+12
4162   40095264768  BTC-USD  1.407782e+12
4163   40593063077  BTC-USD  1.372759e+12
4164   50343575552  BTC-USD  1.350833e+12
==================================================

Null values in df:
date             0
open             0
high             0
low              0
close            0
volume           0
ticker           0
market_cap    3798
dtype: int64

# Feature Engineering

# Model 

### a) Simple rule-based model using `Monte carlo`

In [15]:
%run notebooks/demo_scenario_engine.py

Asset: BTC
Distribution: {'dist': 'normal', 'mu': 0.001199367417760348, 'sigma': 0.03543838238715027, 'n': 4164}
Summary: {'start_price': 67479.5546875, 'horizon_days': 30, 'n_scenarios': 90000, 'terminal_mean': 71188.57621949607, 'terminal_median': 69815.3760437214, 'terminal_p05': 50832.04604392506, 'terminal_p50': 69815.3760437214, 'terminal_p95': 96095.61329005277}
Terminal min / max: 32639.567256957067 159778.8869727989

### b) trained `XGBoost Model`

# Agent Decision Logic

In [ ]:

%run notebooks/run_allocation_on_csv_data.py

Loaded symbols: ['BTC', 'ETH', 'BNB', 'XRP', 'SOL', 'DOGE', 'ADA', 'LINK', 'AVAX', 'FLOKI']
Usable assets: ['BTC', 'ETH', 'BNB', 'XRP', 'SOL', 'DOGE', 'ADA', 'LINK', 'AVAX', 'FLOKI']

RiskTolerance = conservative
  ADA: 0.093939
  AVAX: 0.098036
  BNB: 0.115147
  BTC: 0.112838
  DOGE: 0.096632
  ETH: 0.099607
  FLOKI: 0.090338
  LINK: 0.101650
  SOL: 0.095518
  XRP: 0.096297
  SUM: 1.000000

RiskTolerance = moderate
  ADA: 0.096994
  AVAX: 0.099069
  BNB: 0.107127
  BTC: 0.105989
  DOGE: 0.098539
  ETH: 0.099803
  FLOKI: 0.095355
  LINK: 0.100961
  SOL: 0.097970
  XRP: 0.098193
  SUM: 1.000000

RiskTolerance = aggressive
  ADA: 0.098477
  AVAX: 0.099505
  BNB: 0.103523
  BTC: 0.102904
  DOGE: 0.099332
  ETH: 0.099847
  FLOKI: 0.097794
  LINK: 0.100500
  SOL: 0.099048
  XRP: 0.099069
  SUM: 1.000000